language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-android-gradle' ]; then cd .. && eval "mv $currentfolder generator-android-gradle" && cd generator-android-gradle; fi

